version: '2'
services:
    empcrudmvcapp-app:
        image: empcrudmvcapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://empcrudmvcapp-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    empcrudmvcapp-mssql:
        extends:
            file: mssql.yml
            service: empcrudmvcapp-mssql
